name = "http"
grammar = "http"
path_suffixes = ["http"]
language_servers = ["http-lsp"]
line_comments = ["### "]

brackets = [
    { start = "\"", end = "\"", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = false },
    { start = "<", end = ">", close = true, newline = false },
]
